spring:
  profiles:
    active: ${env:dev}
  application:
    name: star
app:
  id: ${spring.application.name}
server:
  port: 18001
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

---
spring:
  profiles: dev

---
spring:
  profiles: prod