spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.120.31:3306/star?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    password: star#2020
    #连接池的配置信息,应用到上面所有数据源中
    #初始化大小,最小,最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
    filters: stat,wall
    #通过connectProperties属性来打开mergeSql功能;慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
        loginUsername: root
        loginPassword: star#2020
        #IP白名单(没有配置或者为空,则允许所有访问)
        allow:
        #IP黑名单 (存在共同时,deny优先于allow)
        deny:
        #是否可以重置数据源
        resetEnable: false
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true


#图片保存路径
image-upload-url: /home/image
#image-upload-url: D:\spp

jackson:
  time-zone: GMT+8


mybatis-plus:
  typeAliasesPackage: com.star.module.*.entity
  mapper-locations: classpath:/com/star/module/*/dao/impl/*.xml
#  type-aliases-package: com.jgpt.module.spp

swagger:
  enable: true

logging:
  config: classpath:config/logback-spring.xml


